name: proper use of variables(tokens and environment variables)

on: push

jobs: 
  deploy_staging:
    runs-on: ubuntu-latest
    name: staging
    env:
     AWS_REGION: us-east-1
     CONTAINER_NAME: nice-app-service
   steps:
     - name: checkout the code
       uses: actions/checkout@v4
     - name: configure AWS credentials
       uses: aws-actions/configure=aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_REGION_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_REGION_ACCESS_KEY}}
         aws-region: ${{ env.AWS_REGION }}
       
       
